### ISSUE TITLE
Stanford records won't load into prod

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-traject#74]
Nothing happens when adding Stanford records ```https://s3-us-west-2.amazonaws.com/dlme-metadata-stage/output-49528ebb-4cbb-434f-a26d-70391b4e5ff6.ndjson``` to prod environment. This might be caused by trying to get `agg_preview` via IIIF for Stanford maps. Getting previews via druid might be easier: ```https://stacks.stanford.edu/file/druid:#{DRUID}/preview.jpg```

The issue is likely in ```dlme-traject/stanford_mods_config.rg``` or possibly ```dlme-transform/lib/macros/iiif.rb```

**Comment by anarchivist** [comment]
It looks like part of the issue is that some non-JSON data is included in the ndjson file:

```
D, [2019-04-15T13:59:35.576417 #23] DEBUG -- : DLME::Utils.fetch_json(https://purl.stanford.edu/pm625tf0784/iiif/manifest) (396.9ms)
IIIF Manifest not found: Unexpected response type 'text/html' for https://purl.stanford.edu/pm625tf0784/iiif/manifest
D, [2019-04-15T13:59:35.741234 #23] DEBUG -- : DLME::Utils.fetch_json(https://purl.stanford.edu/pm625tf0784/iiif/manifest) (164.5ms)
curtido:Downloads matienzo$ head -n 5 output-49528ebb-4cbb-434f-a26d-70391b4e5ff6.ndjson
D, [2019-04-15T13:59:35.576417 #23] DEBUG -- : DLME::Utils.fetch_json(https://purl.stanford.edu/pm625tf0784/iiif/manifest) (396.9ms)
IIIF Manifest not found: Unexpected response type 'text/html' for https://purl.stanford.edu/pm625tf0784/iiif/manifest
D, [2019-04-15T13:59:35.741234 #23] DEBUG -- : DLME::Utils.fetch_json(https://purl.stanford.edu/pm625tf0784/iiif/manifest) (164.5ms)
IIIF Manifest not found: Unexpected response type 'text/html' for https://purl.stanford.edu/pm625tf0784/iiif/manifest
```

It seems like the logger is writing to `:debug` log level by  [`DLME::Utils.fetch_json`](https://github.com/sul-dlss/dlme-transform/blob/master/lib/dlme_utils.rb#L20),  and the `puts` statement in [`Macros::IIIF.grab_iiif_manifest`](https://github.com/sul-dlss/dlme-transform/blob/master/lib/macros/iiif.rb#L14) is writing to STDOUT with the `puts` statement. These are changes we need to make even if we modify the Stanford macros.
